# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Build
      run: go build -v ./...

    - name: Run Tests
        run: go test -coverpkg=./... -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Check for coverage.out in any directory
      run: |
        found_file=$(find . -name "coverage.out" -print -quit)
        if [ -n "$found_file" ]; then
          echo "coverage.out exists in at least one directory at location: $found_file"
        else
          echo "coverage.out does not exist in any directory"
          # You can add additional debugging information or commands here
        fi
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

